### ISSUE TITLE
[PE-D][Tester B] Not optimised for fast typists

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F15-1/tp#230]
Delete Emergency has an unnecessarily long command name, could be reduced to something shorter like demergency, or deleteem.
`deleteemergency INDEX`

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: Timenikhil/ped#8

**Comment by benjiBase** [comment]
fast typist are able to type fast hence they should have no problem typing deleteemergency as compared to demergency or deleteem. The purpose of making it long is so that nurses are well aware of what they are typing and what it will to our system.

![image](https://github.com/user-attachments/assets/200bcf76-963c-4eb1-8632-dfcac4ce2c6d)
